"""All ORM models. Importing this package registers every table on Base.metadata."""

from overtake.db.base import Base
from overtake.models.fpl import (
    CHIPS,
    POSITIONS,
    Fixture,
    Gameweek,
    HttpCacheEntry,
    League,
    LeagueMember,
    Manager,
    ManagerChip,
    ManagerHistory,
    ManagerPick,
    ManagerTransfer,
    Player,
    PlayerGameweekStat,
    RawSnapshot,
    Team,
    UserLeague,
)
from overtake.models.identity import (
    AGE_BANDS,
    AnalyticsEvent,
    AuthToken,
    LlmSpend,
    Session,
    StripeEvent,
    Subscription,
    UsageCounter,
    User,
)
from overtake.models.outputs import (
    ARCHETYPES,
    Brief,
    Conversation,
    Job,
    LeagueMemory,
    Projection,
    ProjectionAccuracy,
    RivalProfile,
    Simulation,
)

__all__ = [
    "AGE_BANDS",
    "ARCHETYPES",
    "CHIPS",
    "POSITIONS",
    "AnalyticsEvent",
    "AuthToken",
    "Base",
    "Brief",
    "Conversation",
    "Fixture",
    "Gameweek",
    "HttpCacheEntry",
    "Job",
    "League",
    "LeagueMember",
    "LeagueMemory",
    "LlmSpend",
    "Manager",
    "ManagerChip",
    "ManagerHistory",
    "ManagerPick",
    "ManagerTransfer",
    "Player",
    "PlayerGameweekStat",
    "Projection",
    "ProjectionAccuracy",
    "RawSnapshot",
    "RivalProfile",
    "Session",
    "Simulation",
    "StripeEvent",
    "Subscription",
    "Team",
    "UsageCounter",
    "User",
    "UserLeague",
]
