"""Rebuild the Alembic baseline migration from the current models.

The baseline is a generated file. Every migration *after* it is written by hand;
this script exists only so the pre-launch baseline can be kept in step with the
models without a live PostgreSQL server to autogenerate against.

Usage (from api/):  python ../scripts/rebuild_baseline_migration.py
Then verify:        alembic upgrade head  &&  pytest tests/unit/test_migrations.py
"""

from __future__ import annotations

import pathlib
import sys

from alembic.autogenerate import api as autogen_api
from alembic.operations import ops
from alembic.runtime.migration import MigrationContext
from sqlalchemy.sql.ddl import sort_tables_and_constraints

from overtake.models import Base

HEADER = '''"""baseline schema

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-02

The complete Overtake schema. The table DDL below is generated from the
SQLAlchemy models by scripts/rebuild_baseline_migration.py; the PostgreSQL-only
additions (the citext extension and the partial indexes) are appended by hand
because they have no portable equivalent.

Later migrations are written by hand, not regenerated.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import overtake.db.types

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # CITEXT backs the case-insensitive email column.
        op.execute("CREATE EXTENSION IF NOT EXISTS citext")

'''

FOOTER = '''
    if bind.dialect.name == "postgresql":
        # At most one live subscription per user. Enforced in the billing
        # service too, but the database is the backstop that cannot be bypassed.
        op.execute(
            "CREATE UNIQUE INDEX uq_subscriptions_one_active_per_user "
            "ON subscriptions (user_id) "
            "WHERE status IN ('active','trialing','past_due')"
        )
        # Soft-deleted users are read only by the purge job.
        op.execute(
            "CREATE INDEX ix_users_deleted_at ON users (deleted_at) "
            "WHERE deleted_at IS NOT NULL"
        )
        # The queue only ever scans open jobs.
        op.execute(
            "CREATE INDEX ix_jobs_pending ON jobs (run_after) WHERE completed_at IS NULL"
        )


def downgrade() -> None:
    # Dropping every table is destructive and must be a deliberate manual act,
    # not something a mistyped `alembic downgrade` can do.
    raise RuntimeError("Downgrade of the baseline migration is not supported.")
'''


def render() -> str:
    metadata = Base.metadata
    tables = [
        t
        for (t, _fks) in sort_tables_and_constraints(list(metadata.tables.values()))
        if t is not None
    ]

    upgrade_ops = ops.UpgradeOps(ops=[])
    for table in tables:
        upgrade_ops.ops.append(ops.CreateTableOp.from_table(table))
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            upgrade_ops.ops.append(ops.CreateIndexOp.from_index(index))

    context = MigrationContext.configure(dialect_name="postgresql", opts={})
    code = autogen_api.render_python_code(upgrade_ops, migration_context=context)
    code = code.replace(
        "# ### commands auto generated by Alembic - please adjust! ###",
        "# --- tables and indexes (generated from the models) ---",
    )
    code = code.replace("# ### end Alembic commands ###", "")
    # render_python_code already indents statement bodies by four spaces but
    # leaves the leading comment flush left; only that first line needs padding.
    lines = code.splitlines()
    body_lines = [
        ("    " + line if i == 0 and line.strip() else line) for i, line in enumerate(lines)
    ]
    body = "\n".join(body_lines)
    if any(line.startswith("        op.create_table") for line in body_lines):
        raise SystemExit("refusing to write: generated DDL is over-indented")
    return HEADER + body + FOOTER


def main() -> int:
    target = pathlib.Path(__file__).resolve().parents[1] / "api/alembic/versions/0001_baseline.py"
    target.write_text(render(), encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
